apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: devops-toolkit
spec:
  scaleTargetRef:
    apiVersion: apps/v1 # Default
    kind: Deployment # Default
    name: devops-toolkit
  pollingInterval: 5 # Default 30
  cooldownPeriod: 30 # Default 300
  minReplicaCount: 1 # Default 0
  maxReplicaCount: 10 # Default 100
  triggers:
  - type: prometheus
    metadata:
      serverAddress: http://prometheus-server.monitoring
      metricName: traefik_service_requests_total
      threshold: "10"
      query: max(irate(traefik_service_requests_total{service="production-devops-toolkit-80@kubernetes"}[5m]))
