apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: mysql-scaledobject
  namespace: default
  labels:
    deploymentName: dummy
spec:
  maxReplicaCount: 4
  pollingInterval: 3  # Optional. Default: 30 seconds
  cooldownPeriod:  5 # Optional. Default: 300 seconds
  scaleTargetRef:
    name: dummy
  triggers:
    - type: mysql
      metadata:
        username: "root"
        passwordFromEnv: MYSQL_PASSWORD
        host: "mysql.default.svc.cluster.local"
        dbName: "mysql"
        port: "3306"
        queryValue: "5"
        query: "SELECT CEIL(COUNT(*) / 10) FROM test WHERE state='QUEUED'"
---