apiVersion: v2
name: redis
description: A Helm chart for deploying Redis on Kubernetes
type: application
version: 0.1.0

dependencies:
  - name: redis
    version: 17.6.0
    repository: https://charts.bitnami.com/bitnami